---
title: "ValueGuidedConstrual"
output: html_document
date: "2024-05-03"
---

Let us take a new look at the data of Ho et al. 2022
and test whether environmental entropy has an impact on the awareness of subsequent stimuli 

```{r read in data}

library(dplyr)

maze_meta_data = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiment_1_data.csv')

temp=maze_meta_data %>% group_by(grid,obstacle) %>% summarise(goal_dist= mean(goal_dist), start_dist= mean(start_dist),dVGC= mean(dynamic_vgc_weight), wall_dist= mean(walls_dist), center_dist= mean(center_dist))

cor(temp$goal_dist, temp$dVGC)
cor(temp$start_dist, temp$dVGC)
cor(temp$wall_dist, temp$dVGC,method= 'spearman')
cor(temp$center_dist, temp$dVGC,method= 'spearman')
```

```{r read in new mazes and test associations}

library(ggplot2)

maze_meta_data = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/new_mazes_stats.csv')

maze_meta_data= maze_meta_data[-1]
maze_meta_data$lateralized= as.factor(maze_meta_data$lateralized)

# Plot the individuals
jitter_pos=position_jitter(width = .2, height = 0, seed = 1)

ggplot(maze_meta_data, aes(x=lateralized, y=goal_dist, color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("distance to goal") + scale_x_discrete(breaks=c("0","1"),
        labels=c("non-lateralized", "lateralized")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_goal_distance.pdf', device = "pdf", width= 5, height =5)

ggplot(maze_meta_data, aes(x=lateralized, y=start_dist, color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("distance to start") + scale_x_discrete(breaks=c("0","1"),
        labels=c("non-lateralized", "lateralized")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_start_distance.pdf', device = "pdf", width= 5, height =5)


ggplot(maze_meta_data, aes(x=lateralized, y=wall_dist, color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("distance to wall") + scale_x_discrete(breaks=c("0","1"),
        labels=c("non-lateralized", "lateralized")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_wall_distance.pdf', device = "pdf", width= 5, height =5)


ggplot(maze_meta_data, aes(x=lateralized, y=center_dist, color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("distance to centre") + scale_x_discrete(breaks=c("0","1"),
        labels=c("non-lateralized", "lateralized")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_centre_distance.pdf', device = "pdf", width= 5, height =5)

ggplot(maze_meta_data, aes(x=lateralized, y= log10(dVGC), color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("log 10 dynamic VGC") + scale_x_discrete(breaks=c("0","1"),
        labels=c("non-lateralized", "lateralized")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_dynamic_VGC.pdf', device = "pdf", width= 5, height =5)


maze_lateralization = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/Summary_info_lateralized_grids.csv')


maze_lateralization$Lateralized = plyr::mapvalues(maze_lateralization$Lateralized, c(0,1), c('non-lateralized', 'lateralized'))
ggplot(maze_lateralization, aes(Effect, group= Lateralized, color= Lateralized, fill=Lateralized, alpha=0.5)) +
  geom_histogram(aes( color= Lateralized, fill=Lateralized, group= Lateralized,), alpha= 0.5, bins = 20) +
  theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') +
  labs(x = "lateralized index", y = "number of mazes")  + ggpubr::theme_classic2() +
  ggtitle("") + scale_fill_manual(values=c('#B9E615', '#F36A17')) + scale_color_manual(values=c('#B9E615', '#F36A17'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/hist_of_laterailzed_index_mazes.pdf', device = "pdf", width= 6, height =5)


maze_meta_data$log10dVGC= maze_meta_data$dVGC

BayesFactor::generalTestBF(log10dVGC ~ goal_dist*lateralized,  data=maze_meta_data, whichModels = "top")
# weak evidence
# below 1/10 strong in favour of effect

BayesFactor::generalTestBF(log10dVGC ~ start_dist*lateralized,  data=maze_meta_data, whichModels = "top")

BayesFactor::generalTestBF(log10dVGC ~ wall_dist*lateralized,  data=maze_meta_data, whichModels = "top")

BayesFactor::generalTestBF(log10dVGC ~ center_dist*lateralized,  data=maze_meta_data, whichModels = "top")

# all models return ambiguous evidence!!!! 


# biggest effect is start distance  spearman rho of -0.33 but dose not interact with type of maze as seen in above analysis
cor.test(maze_meta_data$goal_dist[maze_meta_data$lateralized==1], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==1]), method = 'spearman')

cor.test(maze_meta_data$goal_dist[maze_meta_data$lateralized==0], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==0]), method = 'spearman')

cor.test(maze_meta_data$start_dist[maze_meta_data$lateralized==0], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==0]), method = 'spearman')

cor.test(maze_meta_data$start_dist[maze_meta_data$lateralized==1], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==1]), method = 'spearman')

cor.test(maze_meta_data$wall_dist[maze_meta_data$lateralized==0], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==0]), method = 'spearman')

cor.test(maze_meta_data$wall_dist[maze_meta_data$lateralized==1], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==1]), method = 'spearman')

cor.test(maze_meta_data$center_dist[maze_meta_data$lateralized==0], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==0]), method = 'spearman')

cor.test(maze_meta_data$center_dist[maze_meta_data$lateralized==1], log10(maze_meta_data$dVGC[maze_meta_data$lateralized==1]), method = 'spearman')


ggplot(maze_meta_data, aes(x=goal_dist, y= log10(dVGC), color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("log 10 dynamic VGC") + xlab('distance to goal')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) +
  stat_smooth(aes(color=lateralized, fill= lateralized), linetype = 'dashed', method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#B9E615', '#F36A17'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_goal_distance_dynamic_VGC.pdf', device = "pdf", width= 5, height =5)

ggplot(maze_meta_data, aes(x=start_dist, y= log10(dVGC), color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("log 10 dynamic VGC") + xlab('distance to start')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) +
  stat_smooth(aes(color=lateralized, fill= lateralized), linetype = 'dashed', method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#B9E615', '#F36A17'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_start_distance_dynamic_VGC.pdf', device = "pdf", width= 5, height =5)


ggplot(maze_meta_data, aes(x=wall_dist, y= log10(dVGC), color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("log 10 dynamic VGC") + xlab('distance to walls')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) +
  stat_smooth(aes(color=lateralized, fill= lateralized), linetype = 'dashed', method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#B9E615', '#F36A17'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_wall_distance_dynamic_VGC.pdf', device = "pdf", width= 5, height =5)


ggplot(maze_meta_data, aes(x=center_dist, y= log10(dVGC), color=lateralized, fill= lateralized))+  theme_classic() + xlab("") + geom_point(shape=21, color="white", size=5, position = jitter_pos, alpha=0.5)  + ylab("log 10 dynamic VGC") + xlab('distance to centre')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) +
  stat_smooth(aes(color=lateralized, fill= lateralized), linetype = 'dashed', method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#B9E615', '#F36A17'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_centre_distance_dynamic_VGC.pdf', device = "pdf", width= 5, height =5)


```



```{r Calculate Hamming distance}

json_data <- rjson::fromJSON(file='~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiments/mazes/mazes_Lateralized.json')

json_data2 <- rjson::fromJSON(file='~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiments/mazes/mazes_Nonlateralized.json')

json_data <-append(json_data, json_data2)
# function that takes in json inputs and converts to matrix for simple math
json2matrix <- function(mazeA){
  m=t(matrix(unlist(strsplit(mazeA, split='')), nrow = 11))
  return(m)
}

# compute hamming distance between mazes to see how similar they are perceptually 
hamming_distance <- function(mazeA, mazeB){
  m=dim(mazeA)[1]
  n=dim(mazeA)[2]
  
  if(dim(mazeA)[1] != dim(mazeB)[1] || dim(mazeA)[2] != dim(mazeB)[2]) {
    stop("inputs not the same size")
  }
  # binarize matrix
  mazeA[mazeA!='.']=1
  mazeB[mazeB!='.']=1
  
  mazeA[mazeA=='.']=0
  mazeB[mazeB=='.']=0
  
  # get diff
  diffmaze= matrix(as.numeric(mazeA), nrow = 11)- matrix(as.numeric(mazeB), nrow = 11)
  hamming_dist= sum(abs(diffmaze))

  return(hamming_dist)
}

matrix_mazes=lapply(json_data, json2matrix)

hamming_dist_mazes= matrix(, nrow=length(json_data)*length(json_data), 3)
count=1
for (i in 1:length(json_data)){
  for (j in 1:length(json_data)){
    hamming_dist_mazes[count,1]= i
    hamming_dist_mazes[count,2]= j
    hamming_dist_mazes[count,3]= hamming_distance(matrix_mazes[[i]], matrix_mazes[[j]])
    count=count+1
  }
}

hamming_dist_mazes= as.data.frame(hamming_dist_mazes)
colnames(hamming_dist_mazes)= c('x', 'y', 'hamming_dist')
library(ggplot2)

ggplot(hamming_dist_mazes, aes(x, y, fill= hamming_dist)) + 
  geom_tile() + scale_y_reverse()+  theme_void() + colorspace::scale_fill_continuous_sequential(palette= 'Lajolla', rev= FALSE, limits= c(0, 50)) + geom_hline(aes(yintercept = 12.5), colour = 'white') + geom_vline(aes(xintercept = 12.5), colour = 'white') + 
  theme(legend.key.height = unit(1, "cm"),
        legend.title = element_text(size = 12, angle = 270),
        legend.title.align = 0.5,
        legend.direction = "vertical", legend.text.position = 'right',
        legend.title.position = 'right') + annotate("text", x = 7, y=-0.75, label = "lateralized") + annotate("text", x = 7+12, y=-0.75, label = "non-lateralized") + annotate("text", x = -0.75, y=7+12, label = "non-lateralized", angle = 90) + annotate("text", x = -0.75, y=7, label = "lateralized", angle = 90)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/results/R_plot_Hamming_distance_between_mazes.pdf', device = "pdf", width= 6, height =5)

```


```{r check lateralization of original experiment 1}

# original experiment with awareness probes 

library(dplyr)

data = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiment_1_data.csv')

temp=data %>% group_by(grid,obstacle) %>% summarise(goal_dist= mean(goal_dist), start_dist= mean(start_dist), wall_dist= mean(walls_dist), center_dist= mean(center_dist), dVGC= mean(dynamic_vgc_weight), sVGC= mean(static_vgc_weight))

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/original_stimuli_stats.csv', na.strings = 'NaN')

maze_stats=maze_stats[order(maze_stats$grid),]

dictionary_of_maze=unique(unlist(strsplit(maze_stats$grid, '-0')))[2:17]
dictionary_of_maze[1] = 'grid-0'

maze_stats=maze_stats[!is.na(maze_stats$side),]
temp=maze_stats %>% group_by(grid, side) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

latmazes= data.frame(grid = unique(temp$grid),
  lat_dVGC =abs((temp$sumdVGC[temp$side=='R'] - temp$sumdVGC[temp$side=='L']) / (temp$sumdVGC[temp$side=='R'] + temp$sumdVGC[temp$side=='L'])),
  lat_sVGC= abs((temp$sumsVGC[temp$side=='R'] - temp$sumsVGC[temp$side=='L']) / (temp$sumsVGC[temp$side=='R'] + temp$sumsVGC[temp$side=='L'])))

# make sure the two model predictions are related!
cor.test(latmazes$lat_dVGC, latmazes$lat_sVGC)

index_mazes=paste(data$grid, data$obstacle)

data$lateralized_values_dVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_dVGC))
data$lateralized_values_sVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_sVGC))


data$lat_dVGC_scaled= scale(data$lateralized_values_dVGC)[,1]
data$lat_sVGC_scaled= scale(data$lateralized_values_sVGC)[,1]

# need to add subject intercept!!
lm0= lmer(attention_N ~  (1 | grid)+ (1 | sessionId), data= data)
lm1= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

# need to add subject intercept!!
lm0= lmer(attention_N ~  (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# trending effect but non-significant! 



# add in nuissance covariates 
# need to add subject intercept!!
lm0= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + static_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

lm0= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# no effect! 


# plot sVGC effect 
data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, obstacle) %>% summarise(mean_awareness= mean(attention), mean_sVGC= mean(static_vgc_weight), mean_dVGC= mean(dynamic_vgc_weight),lat_sVGC= mean(lateralized_values_sVGC), lat_dVGC= mean(lateralized_values_dVGC))

# remove intercept of each maze 
temp=data_plot %>% group_by(grid) %>% summarise(mean_awareness= mean(mean_awareness), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_awareness= data_plot$mean_awareness-  rep(temp$mean_awareness, each=7)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=7)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=7)

data_plot$lat_sVGC_scaled = factor(round(data_plot$lat_sVGC,2), levels = sort(unique(round(data_plot$lat_sVGC,2))) )
data_plot$lat_dVGC_scaled = factor(round(data_plot$lat_dVGC,2), levels = sort(unique(round(data_plot$lat_dVGC,2))) )


x <- seq(0, 1, length.out = length(unique(data_plot$lat_sVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_sVGC_scaled, fill= lat_sVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment1_interaction_plot_continuous_lateralized_sVGC.pdf', device = "pdf", width= 6, height =5)


x <- seq(0, 1, length.out = length(unique(data_plot$lat_dVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_dVGC, y= mean_awareness, color=lat_dVGC_scaled, fill= lat_dVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)


ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment1_interaction_plot_continuous_lateralized_dVGC.pdf', device = "pdf", width= 6, height =5)


```



```{r check lateralization of original experiment 2}

#expriment with awareness probes, but obstacles disapear after participants starts to move

library(dplyr)
library(ggplot2)

data = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiment_2_data.csv')

temp=data %>% group_by(grid,obstacle) %>% summarise(goal_dist= mean(goal_dist), start_dist= mean(start_dist), wall_dist= mean(walls_dist), center_dist= mean(center_dist), dVGC= mean(dynamic_vgc_weight), sVGC= mean(static_vgc_weight))

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/original_stimuli_stats.csv', na.strings = 'NaN')

maze_stats=maze_stats[order(maze_stats$grid),]

dictionary_of_maze=unique(unlist(strsplit(maze_stats$grid, '-0')))[2:17]
dictionary_of_maze[1] = 'grid-0'

maze_stats=maze_stats[!is.na(maze_stats$side),]
temp=maze_stats %>% group_by(grid, side) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

latmazes= data.frame(grid = unique(temp$grid),
  lat_dVGC =abs((temp$sumdVGC[temp$side=='R'] - temp$sumdVGC[temp$side=='L']) / (temp$sumdVGC[temp$side=='R'] + temp$sumdVGC[temp$side=='L'])),
  lat_sVGC= abs((temp$sumsVGC[temp$side=='R'] - temp$sumsVGC[temp$side=='L']) / (temp$sumsVGC[temp$side=='R'] + temp$sumsVGC[temp$side=='L'])))

# make sure the two model predictions are related!
cor.test(latmazes$lat_dVGC, latmazes$lat_sVGC)

index_mazes=paste(data$grid, data$obstacle)

data$lateralized_values_dVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_dVGC))
data$lateralized_values_sVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_sVGC))


data$lat_dVGC_scaled= scale(data$lateralized_values_dVGC)[,1]
data$lat_sVGC_scaled= scale(data$lateralized_values_sVGC)[,1]

# need to add subject intercept!!
lm0= lmer(attention_N ~  (1 | grid)+ (1 | sessionId), data= data)
lm1= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

# need to add subject intercept!!
lm0= lmer(attention_N ~  (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(attention_N ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# non-significant! 



# add in nuissance covariates 
# need to add subject intercept!!
lm0= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + static_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

lm0= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(attention_N ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z, data= data)
lm2= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(attention_N ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# no effect! 


# plot sVGC effect 
data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, obstacle) %>% summarise(mean_awareness= mean(attention), mean_sVGC= mean(static_vgc_weight), mean_dVGC= mean(dynamic_vgc_weight),lat_sVGC= mean(lateralized_values_sVGC), lat_dVGC= mean(lateralized_values_dVGC))

# remove intercept of each maze 
temp=data_plot %>% group_by(grid) %>% summarise(mean_awareness= mean(mean_awareness), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_awareness= data_plot$mean_awareness-  rep(temp$mean_awareness, each=7)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=7)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=7)

data_plot$lat_sVGC_scaled = factor(round(data_plot$lat_sVGC,2), levels = sort(unique(round(data_plot$lat_sVGC,2))) )
data_plot$lat_dVGC_scaled = factor(round(data_plot$lat_dVGC,2), levels = sort(unique(round(data_plot$lat_dVGC,2))) )


x <- seq(0, 1, length.out = length(unique(data_plot$lat_sVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_sVGC_scaled, fill= lat_sVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment2_interaction_plot_continuous_lateralized_sVGC.pdf', device = "pdf", width= 6, height =5)


x <- seq(0, 1, length.out = length(unique(data_plot$lat_dVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_dVGC, y= mean_awareness, color=lat_dVGC_scaled, fill= lat_dVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)


ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment1_interaction_plot_continuous_lateralized_dVGC.pdf', device = "pdf", width= 6, height =5)


```




# cant fit experiment 3 bc critical mazes have no variance asscoitaed with lateralization (3 levels for dVGC and 2 sVGC)

# let us skip straight to exp 4 which uses all mazes 



```{r check lateralization of original experiment 4}

#expriment with awareness probes, but obstacles disapear after participants starts to move

library(dplyr)
library(ggplot2)

data = read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/experiment_4a_ht_data.csv')

temp=data %>% group_by(grid,obstacle) %>% summarise(goal_dist= mean(goal_dist), start_dist= mean(start_dist), wall_dist= mean(walls_dist), center_dist= mean(center_dist), dVGC= mean(dynamic_vgc_weight), sVGC= mean(static_vgc_weight))

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/original_stimuli_stats.csv', na.strings = 'NaN')

maze_stats=maze_stats[order(maze_stats$grid),]

dictionary_of_maze=unique(unlist(strsplit(maze_stats$grid, '-0')))[2:17]
dictionary_of_maze[1] = 'grid-0'

maze_stats=maze_stats[!is.na(maze_stats$side),]
temp=maze_stats %>% group_by(grid, side) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

latmazes= data.frame(grid = unique(temp$grid),
  lat_dVGC =abs((temp$sumdVGC[temp$side=='R'] - temp$sumdVGC[temp$side=='L']) / (temp$sumdVGC[temp$side=='R'] + temp$sumdVGC[temp$side=='L'])),
  lat_sVGC= abs((temp$sumsVGC[temp$side=='R'] - temp$sumsVGC[temp$side=='L']) / (temp$sumsVGC[temp$side=='R'] + temp$sumsVGC[temp$side=='L'])))

# make sure the two model predictions are related!
cor.test(latmazes$lat_dVGC, latmazes$lat_sVGC)

index_mazes=paste(data$grid, data$obstacle)

data$lateralized_values_dVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_dVGC))
data$lateralized_values_sVGC=as.numeric(plyr::mapvalues(data$grid, dictionary_of_maze, latmazes$lat_sVGC))


data$lat_dVGC_scaled= scale(data$lateralized_values_dVGC)[,1]
data$lat_sVGC_scaled= scale(data$lateralized_values_sVGC)[,1]

# need to add subject intercept!!
lm0= lmer(log_hoverduration ~  (1 | grid)+ (1 | sessionId), data= data)
lm1= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z, data= data)
lm2= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

# need to add subject intercept!!
lm0= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z, data= data)
lm2= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(log_hoverduration ~  (1 | grid) + (1 | sessionId)+ dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)



# add in nuissance covariates 
# need to add subject intercept!!
lm0= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(log_hoverduration ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + static_vgc_weight_Z, data= data)
lm2= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z + lat_sVGC_scaled, data= data)
lm3= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + static_vgc_weight_Z * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we see a smaller (but still significant effect!)

lm0= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId), data= data)
lm1= lmer(log_hoverduration ~ start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist + (1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z, data= data)
lm2= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z + lat_dVGC_scaled, data= data)
lm3= lmer(log_hoverduration ~  start_dist_Z+ goal_dist_Z + walls_dist_Z + center_dist +(1 | grid) + (1 | sessionId) + dynamic_vgc_weight_Z * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# no effect now but trending! 


# plot sVGC effect 
data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, obstacle) %>% summarise(mean_hovdur= mean(log_hoverduration, na.rm= TRUE), mean_sVGC= mean(static_vgc_weight), mean_dVGC= mean(dynamic_vgc_weight),lat_sVGC= mean(lateralized_values_sVGC), lat_dVGC= mean(lateralized_values_dVGC))

# remove intercept of each maze 
temp=data_plot %>% group_by(grid) %>% summarise(mean_hovdur= mean(mean_hovdur, na.rm= TRUE), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_hovdur= data_plot$mean_hovdur-  rep(temp$mean_hovdur, each=7)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=7)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=7)

data_plot$lat_sVGC_scaled = factor(round(data_plot$lat_sVGC,2), levels = sort(unique(round(data_plot$lat_sVGC,2))) )
data_plot$lat_dVGC_scaled = factor(round(data_plot$lat_dVGC,2), levels = sort(unique(round(data_plot$lat_dVGC,2))) )


x <- seq(0, 1, length.out = length(unique(data_plot$lat_sVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_sVGC, y= mean_hovdur, color=lat_sVGC_scaled, fill= lat_sVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment4a_interaction_plot_continuous_lateralized_sVGC.pdf', device = "pdf", width= 6, height =5)


x <- seq(0, 1, length.out = length(unique(data_plot$lat_dVGC_scaled)))
pallete_man= c(scales::seq_gradient_pal(high = '#F36A17', low= '#B9E615')(x))
ggplot(data_plot, aes(x=mean_dVGC, y= mean_hovdur, color=lat_dVGC_scaled, fill= lat_dVGC_scaled))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(method='lm', se= FALSE, fullrange = T) +  scale_color_manual(values = pallete_man) + scale_fill_manual(values = pallete_man)


ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/ORIGINAL_experiment4a_interaction_plot_continuous_lateralized_dVGC.pdf', device = "pdf", width= 6, height =5)


```

