---
title: "VGC_behav_analysis"
output: html_document
date: "2024-05-22"
---


# run terminal command: 

cat ~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/0*.csv >> ~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/allDataConcatnated.csv

```{r read in behav data & plot hist of aware reports}

library(dplyr)
library(ggplot2)
data= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/allDataConcatnated.csv', na.strings = 'NaN')


# plot hist of static VGSC

data$Aware.ReportObs.scaled= plyr::mapvalues(data$Aware.ReportObs, c(1,2,3,4,5,6,7,8,9), c(0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1))

data$Lateralized.factor= factor(plyr::mapvalues(data$Lateralized, c(0,1), c('non-lateralized', 'lateralized')), levels = c('non-lateralized', 'lateralized'))

data$binarysVGC= data$sVGC.Obs > 0.5
data$binarysVGC= plyr::mapvalues(data$binarysVGC, c(1,0), c('relevant', 'irrelevant'))

ggplot(data, aes(Aware.ReportObs.scaled, group= binarysVGC, color= binarysVGC, fill=binarysVGC, alpha=0.5)) +
  geom_histogram(aes( color= binarysVGC, fill=binarysVGC, group= binarysVGC), alpha= 0.5, bins = 9, position = 'identity') +
  theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') +
  labs(x = "awareness of obstacle", y = "count")  + ggpubr::theme_classic2() +
  ggtitle("") + scale_fill_manual(values=c('#B9E615', '#F36A17')) + scale_color_manual(values=c('#B9E615', '#F36A17')) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/hist_of_awareness.pdf', device = "pdf", width= 6, height =5)


ggplot(data, aes(Aware.ReportObs.scaled, group= binarysVGC, color= binarysVGC, fill=binarysVGC, alpha=0.5)) +
  geom_histogram(aes( color= binarysVGC, fill=binarysVGC, group= binarysVGC), alpha= 0.5, bins = 9, position = 'identity') +
  theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') +
  labs(x = "awareness of obstacle", y = "count")  + ggpubr::theme_classic2() +
  ggtitle("") + scale_fill_manual(values=c('#B9E615', '#F36A17')) + scale_color_manual(values=c('#B9E615', '#F36A17')) + facet_wrap(~Lateralized.factor)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/hist_of_awareness_by_maze_type.pdf', device = "pdf", width= 12, height =5)


ggplot(data, aes(Aware.ReportObs.scaled, group= binarysVGC, color= binarysVGC, fill=binarysVGC, alpha=0.5)) +
  geom_histogram(aes( color= binarysVGC, fill=binarysVGC, group= binarysVGC), alpha= 0.5, bins = 9, position = 'identity') +
  theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') +
  labs(x = "awareness of obstacle", y = "count")  + ggpubr::theme_classic2() +
  ggtitle("") + scale_fill_manual(values=c('#B9E615', '#F36A17')) + scale_color_manual(values=c('#B9E615', '#F36A17')) + facet_wrap(~Lateralized.factor, nrow = 2)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/hist_of_awareness_by_maze_type2.pdf', device = "pdf", width= 5, height =10)



```



```{r run peliminary model}

library(lme4)

data$sVGC.Obs.zscore= scale(data$sVGC.Obs)[,1]
data$dVGC.Obs.zscore= scale(data$dVGC.Obs)[,1]
data$Lateralized.zscore= scale(data$Lateralized)[,1]

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore * Lateralized.zscore, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# significant interaction effect between awareness and sVGC, better fits (stronger relationship, when lateralized )

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID)+ (1 | Subject.Code) + dVGC.Obs.zscore * Lateralized.zscore, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# we observe the same thing for the dynamic construals 

# note to self dVGC data is VERY VERY VERY skewed should be log transformed!!!! 

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID), data= data[data$Lateralized==0,])
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + log(dVGC.Obs), data= data[data$Lateralized==0,])
anova(lm0,lm1)
sjPlot::tab_model(lm1)

ggplot(data, aes(x=sVGC.Obs.zscore, y= Aware.ReportObs.scaled, color=Lateralized.factor, fill= Lateralized.factor))+  theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (z-scored)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + scale_fill_manual(values=c('#F36A17', '#B9E615')) +
  stat_smooth(aes(color=Lateralized.factor, fill= Lateralized.factor), method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#F36A17', '#B9E615'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_sVGC.pdf', device = "pdf", width= 6, height =5)



ggplot(data, aes(x=dVGC.Obs.zscore, y= Aware.ReportObs.scaled, color=Lateralized.factor, fill= Lateralized.factor))+  theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (z-scored)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + scale_fill_manual(values=c('#F36A17', '#B9E615')) +
  stat_smooth(aes(color=Lateralized.factor, fill= Lateralized.factor), method = "glm",formula = y ~ poly(x, 1),fullrange = T) + scale_color_manual(values=c('#F36A17', '#B9E615'))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_dVGC.pdf', device = "pdf", width= 6, height =5)


```

```{r test for nuissance covariates}

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/new_mazes_stats.csv', na.strings = 'NaN')
maze_stats=rbind(maze_stats,maze_stats)

maze_stats$MazeID= c(rep(unlist(lapply(c(1:12), rep,6)),2), rep(unlist(lapply(c(13:24), rep,6)),2))
maze_stats$Obs.No= as.integer(substr(maze_stats$obstacle, 5, 5))
maze_stats$Obs.No= maze_stats$Obs.No+1 # bc of python index

dictionary_of_maze= paste(maze_stats$lateralized, maze_stats$MazeID, maze_stats$Obs.No)

index_mazes=paste(data$Lateralized, data$MazeID, data$Obs.No)
data$goal_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$goal_dist)
data$start_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$start_dist)
data$wall_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$wall_dist)
data$center_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$center_dist)
data$Optmoves=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$Moves-1)

data$AttendSide=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$AttendSide)
data$TaskIrrGoodSide=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$TaskIrrGoodSide)

data$goal_dist.zscore= scale(as.numeric(data$goal_dist))[,1]
data$start_dist.zscore= scale(as.numeric(data$start_dist))[,1]
data$wall_dist.zscore= scale(as.numeric(data$wall_dist))[,1]
data$center_dist.zscore= scale(as.numeric(data$center_dist))[,1]


# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID)  + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore, data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore * Lateralized.zscore, data= data)
anova(lm0,lm1, lm2, lm3)
sjPlot::tab_model(lm3)


lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore, data= data)
sjPlot::tab_model(lm0)


# lesioning of AIC
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore * Lateralized.zscore, data= data)
lm3.1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID)+ (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore , data= data)
lm3.3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore  + Lateralized.zscore, data= data)
lm3.4= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore  + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.5= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore  + center_dist.zscore + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.6= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore  + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.7= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + start_dist.zscore + wall_dist.zscore + center_dist.zscore + dVGC.Obs.zscore + Lateralized.zscore, data= data)

AIC_lesion=c(AIC(lm3) - AIC(lm3.1),
AIC(lm3.1) - AIC(lm3.2),
AIC(lm3.1) - AIC(lm3.3),
AIC(lm3.1) - AIC(lm3.4),
AIC(lm3.1) - AIC(lm3.5),
AIC(lm3.1) - AIC(lm3.6),
AIC(lm3.1) - AIC(lm3.7))

AICplot= data.frame(AIC= AIC_lesion, lesionedVar= factor(c('dVGC*Lateralized', 'Lateralized', 'dVGC', 'center distance', 'wall distance', 'start distance', 'goal distance'), levels = c('dVGC*Lateralized', 'Lateralized', 'dVGC', 'center distance', 'wall distance', 'start distance', 'goal distance')))

ggplot(AICplot, aes(x=lesionedVar, y=AIC,width=.5 )) + geom_bar(stat = "identity", position=position_dodge(width = 0.5)) + ggpubr::theme_classic2() + scale_color_manual(values='#F36A17') + labs(y="delta AIC", x="lesioned parameter",title="") + theme(text = element_text(size=15), legend.title=element_blank(), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/lesionAIC_plot_dVGC.pdf', device = "pdf", width= 6, height =5)


# lesioning of AIC
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + sVGC.Obs.zscore * Lateralized.zscore, data= data)
lm3.1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore + sVGC.Obs.zscore , data= data)
lm3.3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore + center_dist.zscore  + Lateralized.zscore, data= data)
lm3.4= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore + wall_dist.zscore  + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.5= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ goal_dist.zscore + start_dist.zscore  + center_dist.zscore + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.6= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + goal_dist.zscore  + wall_dist.zscore + center_dist.zscore + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3.7= lmer(Aware.ReportObs.scaled ~  (1 | MazeID)  + start_dist.zscore + wall_dist.zscore + center_dist.zscore + sVGC.Obs.zscore + Lateralized.zscore, data= data)

AIC_lesion=c(AIC(lm3) - AIC(lm3.1),
AIC(lm3.1) - AIC(lm3.2),
AIC(lm3.1) - AIC(lm3.3),
AIC(lm3.1) - AIC(lm3.4),
AIC(lm3.1) - AIC(lm3.5),
AIC(lm3.1) - AIC(lm3.6),
AIC(lm3.1) - AIC(lm3.7))

AICplot= data.frame(AIC= AIC_lesion, lesionedVar= factor(c('sVGC*Lateralized', 'Lateralized', 'sVGC', 'center distance', 'wall distance', 'start distance', 'goal distance'), levels = c('sVGC*Lateralized', 'Lateralized', 'sVGC', 'center distance', 'wall distance', 'start distance', 'goal distance')))

ggplot(AICplot, aes(x=lesionedVar, y=AIC,width=.5 )) + geom_bar(stat = "identity", position=position_dodge(width = 0.5)) + ggpubr::theme_classic2() + scale_color_manual(values='#F36A17') + labs(y="delta AIC", x="lesioned parameter",title="") + theme(text = element_text(size=15), legend.title=element_blank(), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/lesionAIC_plot_sVGC.pdf', device = "pdf", width= 6, height =5)


```



```{r does lateralized size explain var}


data4plot= data[data$binarysVGC=='irrelevant' & data$Lateralized==1,]

ggplot(data4plot, aes(Aware.ReportObs.scaled, group= TaskIrrGoodSide, color= TaskIrrGoodSide, fill=TaskIrrGoodSide, alpha=0.5)) +
  geom_density(aes( color= TaskIrrGoodSide, fill=TaskIrrGoodSide, group= TaskIrrGoodSide), alpha= 0.5, position = 'identity') +
  theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') +
  labs(x = "awareness of obstacle", y = "count")  + ggpubr::theme_classic2() +
  ggtitle("") + scale_fill_manual(values=c('#B9E615', '#5ca814')) + scale_color_manual(values=c('#B9E615', '#5ca814')) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/hist_of_awareness_contextEffects.pdf', device = "pdf", width= 6, height =5)


# part of the bump in awareness reports we observe can be explained by the 'context' where an irrelvant stimulus is surrounded by relevant stimuli (sVGC)

library(lme4)

data$sVGC.Obs.zscore= scale(data$sVGC.Obs)[,1]
data$dVGC.Obs.zscore= scale(data$dVGC.Obs)[,1]
data$Lateralized.zscore= scale(data$Lateralized)[,1]

data4reg= data[!is.na(data$AttendSide) & data$Lateralized==1, ]

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data4reg)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore, data= data4reg)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + AttendSide, data= data4reg)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ dVGC.Obs.zscore, data= data4reg)
anova(lm0,lm1,lm2, lm3)
anova(lm1,lm2)
anova(lm3,lm2)

sjPlot::tab_model(lm2)
sjPlot::tab_model(lm1)

# splitting data by attended side does not explain more variance than sVGC model! 
# this means that people are guiding their attention to stimuli, not hemifield
# despite evidence of spill over effect when irrelevant stimuli are embeded in revelant 

data4reg= data[!is.na(data$AttendSide), ]
jitter_pos=position_jitter(width = .2, height = 0, seed = 1)

ggplot(data4reg, aes(AttendSide, Aware.ReportObs, fill=AttendSide)) + 
theme_classic() + xlab("") + ylab("awareness of obstacle") + scale_x_discrete(breaks=c("0","1"),
        labels=c("not attended", "attended")) + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14), legend.position = 'none') + scale_fill_manual(values=c('#B9E615', '#F36A17')) + geom_boxplot(width=0.1, colour= 'black', outliers = FALSE) 

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/boxplot_of_awareness_contextEffects.pdf', device = "pdf", width= 6, height =5)


```

```{r compute lateralized effect continuous}

library(dplyr)
data= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/allDataConcatnated.csv')
data$grid= data$MazeID-1
data$grid[data$grid>=12] = data$grid[data$grid>=12]-12
data$Aware.ReportObs.scaled= plyr::mapvalues(data$Aware.ReportObs, c(1,2,3,4,5,6,7,8,9), c(0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1))

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/new_mazes_stats.csv')
maze_stats=maze_stats[order(maze_stats$grid),]

temp=maze_stats %>% group_by(grid, side) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

latmazes= data.frame(grid = unique(temp$grid),
  lat_dVGC =abs((temp$sumdVGC[temp$side=='R'] - temp$sumdVGC[temp$side=='L']) / (temp$sumdVGC[temp$side=='R'] + temp$sumdVGC[temp$side=='L'])),
  lat_sVGC= abs((temp$sumsVGC[temp$side=='R'] - temp$sumsVGC[temp$side=='L']) / (temp$sumsVGC[temp$side=='R'] + temp$sumsVGC[temp$side=='L'])))

dictionary_of_maze=unique(paste(maze_stats$lateralized, as.numeric(substr(maze_stats$grid, 7,8))))

# make sure the two model predictions are related!
cor.test(latmazes$lat_dVGC, latmazes$lat_sVGC)

data$grid= data$MazeID-1
data$grid[data$grid>=12] = data$grid[data$grid>=12]-12

index_mazes=paste(data$Lateralized, data$grid)


data$lateralized_values_dVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$lat_dVGC))
data$lateralized_values_sVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$lat_sVGC))


data$sVGC.Obs.zscore= scale(data$sVGC.Obs)[,1]
data$dVGC.Obs.zscore= scale(data$dVGC.Obs)[,1]
data$lat_dVGC_scaled= scale(data$lateralized_values_dVGC)[,1]
data$lat_sVGC_scaled= scale(data$lateralized_values_sVGC)[,1]

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore + lat_sVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ sVGC.Obs.zscore * lat_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# significant lateralization effect!!! 
# this means that beyond the binary categories of lateralization, the relative amount 
# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ dVGC.Obs.zscore + lat_dVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ dVGC.Obs.zscore * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
# significant lateralization effect!!! 
# this means that beyond the binary categories of lateralization, the relative amount 
data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, Lateralized, Obs.No) %>% summarise(mean_awareness= mean(Aware.ReportObs), mean_sVGC= mean(sVGC.Obs), mean_dVGC= mean(dVGC.Obs),lat_sVGC= mean(lateralized_values_sVGC), lat_dVGC= mean(lateralized_values_dVGC))

# remove intercept of each maze 
temp=data_plot %>% group_by(grid, Lateralized) %>% summarise(mean_awareness= mean(mean_awareness), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_awareness= data_plot$mean_awareness-  rep(temp$mean_awareness, each=6)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=6)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=6)

ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_sVGC, fill= lat_sVGC, group = factor(lat_sVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_continuous_lateralized_sVGC.pdf', device = "pdf", width= 7, height =5)

ggplot(data_plot, aes(x=mean_dVGC, y= mean_awareness, color=lat_dVGC, fill= lat_dVGC, group = factor(lat_dVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_continuous_lateralized_dVGC.pdf', device = "pdf", width= 7, height =5)






maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/new_mazes_stats.csv', na.strings = 'NaN')
maze_stats=rbind(maze_stats,maze_stats)

maze_stats$MazeID= c(rep(unlist(lapply(c(1:12), rep,6)),2), rep(unlist(lapply(c(13:24), rep,6)),2))
maze_stats$Obs.No= as.integer(substr(maze_stats$obstacle, 5, 5))
maze_stats$Obs.No= maze_stats$Obs.No+1 # bc of python index

dictionary_of_maze= paste(maze_stats$lateralized, maze_stats$MazeID, maze_stats$Obs.No)

index_mazes=paste(data$Lateralized, data$MazeID, data$Obs.No)
data$goal_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$goal_dist)
data$start_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$start_dist)
data$wall_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$wall_dist)
data$center_dist=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$center_dist)
data$ObjMoves=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, as.numeric(maze_stats$Moves)-1))

data$AttendSide=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$AttendSide)
data$TaskIrrGoodSide=plyr::mapvalues(index_mazes, dictionary_of_maze, maze_stats$TaskIrrGoodSide)

data$goal_dist.zscore= scale(as.numeric(data$goal_dist))[,1]
data$start_dist.zscore= scale(as.numeric(data$start_dist))[,1]
data$wall_dist.zscore= scale(as.numeric(data$wall_dist))[,1]
data$center_dist.zscore= scale(as.numeric(data$center_dist))[,1]

data4reg= data %>% group_by(Subject.Code, Trial.Number, MazeID) %>% summarise(Moves= mean(Moves), lat_sVGC_scaled= mean(lat_sVGC_scaled), Lateralized= mean(Lateralized),lat_dVGC_scaled= mean(lat_dVGC_scaled), start_dist.zscore= mean(start_dist.zscore), goal_dist.zscore= mean(goal_dist.zscore), ObjMoves= mean(ObjMoves))

cor.test(data4reg$lat_dVGC_scaled, data4reg$ObjMoves)
cor.test(data4reg$lat_dVGC_scaled[data4reg$Lateralized==0], data4reg$ObjMoves[data4reg$Lateralized==0])
cor.test(data4reg$lat_dVGC_scaled[data4reg$Lateralized==1], data4reg$ObjMoves[data4reg$Lateralized==1])

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ ObjMoves + dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ ObjMoves + dVGC.Obs.zscore + lat_dVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ ObjMoves + dVGC.Obs.zscore * lat_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

# need to add subject intercept!!
lm0= lmer(Moves ~  (1 | MazeID) + (1 | Subject.Code), data= data4reg)
lm1= lmer(Moves ~  (1 | MazeID) + (1 | Subject.Code)+  lat_sVGC_scaled, data= data4reg)
anova(lm0,lm1)

sjPlot::tab_model(lm1)


```


```{r compute horizontal effect }

library(dplyr)
data= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/allDataConcatnated.csv', na.strings = 'NaN')
data$grid= data$MazeID-1
data$grid[data$grid>=12] = data$grid[data$grid>=12]-12
data$Aware.ReportObs.scaled= plyr::mapvalues(data$Aware.ReportObs, c(1,2,3,4,5,6,7,8,9), c(0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1))

maze_stats= read.csv('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/new_mazes_stats.csv', na.strings = 'NaN')
maze_stats=maze_stats[order(maze_stats$grid),]

temp=maze_stats %>% group_by(grid, side) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

index_mazes=paste(data$Lateralized, data$grid)

latmazes= data.frame(grid = unique(temp$grid),
  lat_dVGC =abs((temp$sumdVGC[temp$side=='R'] - temp$sumdVGC[temp$side=='L']) / (temp$sumdVGC[temp$side=='R'] + temp$sumdVGC[temp$side=='L'])),
  lat_sVGC= abs((temp$sumsVGC[temp$side=='R'] - temp$sumsVGC[temp$side=='L']) / (temp$sumsVGC[temp$side=='R'] + temp$sumsVGC[temp$side=='L'])))

dictionary_of_maze=unique(paste(maze_stats$lateralized, as.numeric(substr(maze_stats$grid, 7,8))))

index_mazes=paste(data$Lateralized, data$grid)
data$lateralized_values_dVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$lat_dVGC))
data$lateralized_values_sVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$lat_sVGC))

latmazesRL=latmazes

maze_stats= maze_stats[!is.na(maze_stats$Quad),]

temp=maze_stats %>% group_by(grid, Quad) %>% summarise(sumdVGC= sum(dVGC), sumsVGC= sum(sVGC))

latmazes= data.frame(grid = unique(temp$grid),
  hlat_dVGC =abs((temp$sumdVGC[temp$Quad=='U'] - temp$sumdVGC[temp$Quad=='L']) / (temp$sumdVGC[temp$Quad=='U'] + temp$sumdVGC[temp$Quad=='L'])),
  hlat_sVGC= abs((temp$sumsVGC[temp$Quad=='U'] - temp$sumsVGC[temp$Quad=='L']) / (temp$sumsVGC[temp$Quad=='U'] + temp$sumsVGC[temp$Quad=='L'])))

dictionary_of_maze=unique(paste(maze_stats$lateralized, as.numeric(substr(maze_stats$grid, 7,8))))

# make sure the two model predictions are related!
cor.test(latmazes$hlat_dVGC, latmazes$hlat_sVGC)

data$grid= data$MazeID-1
data$grid[data$grid>=12] = data$grid[data$grid>=12]-12

data$hor_values_dVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$hlat_dVGC))
data$hor_values_sVGC=as.numeric(plyr::mapvalues(index_mazes, dictionary_of_maze, latmazes$hlat_sVGC))

cor.test(latmazes$hlat_dVGC, latmazesRL$lat_dVGC)
cor.test(latmazes$hlat_sVGC, latmazesRL$lat_sVGC)
# mazes have weak correlations between laterlaization hor and ver

data$sVGC.Obs.zscore= scale(data$sVGC.Obs)[,1]
data$dVGC.Obs.zscore= scale(data$dVGC.Obs)[,1]
data$hor_dVGC_scaled= scale(data$hor_values_dVGC)[,1]
data$hor_sVGC_scaled= scale(data$hor_values_sVGC)[,1]
data$lat_dVGC_scaled= scale(data$lateralized_values_dVGC)[,1]
data$lat_sVGC_scaled= scale(data$lateralized_values_sVGC)[,1]


lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore + hor_sVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore * hor_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)
sjPlot::tab_model(lm2)


lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ dVGC.Obs.zscore + hor_dVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ dVGC.Obs.zscore * hor_dVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3)

sjPlot::tab_model(lm3)

# interaction between hor lat and sVGC


lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code), data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore + lat_sVGC_scaled, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+sVGC.Obs.zscore +  lat_sVGC_scaled+ hor_sVGC_scaled, data= data)
lm4= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore +  lat_sVGC_scaled*sVGC.Obs.zscore+  hor_sVGC_scaled, data= data)
lm5= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+sVGC.Obs.zscore +  lat_sVGC_scaled*sVGC.Obs.zscore+  hor_sVGC_scaled*sVGC.Obs.zscore, data= data)
lm6= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore * lat_sVGC_scaled * hor_sVGC_scaled, data= data)
anova(lm0,lm1, lm2, lm3,lm4,lm5,lm6)

sjPlot::tab_model(lm6)

# significant three way interaction effect between sVGC and laterlaization 

lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1| Subject.Code)+ lat_sVGC_scaled * hor_sVGC_scaled, data= data)

anova(lm0,lm1, lm2)
# sVGC model is still the most parsimonious than a quadrant model (AKA a model where we include ver and hor lateralization effects)

# It seems like the effect of attention is complex informed both by the saliency of the stimuli (aka how useful they are), but these task construals are also susceptible to attentional biases like crowding effects where task irrelevant information will be incoperated into the construal if nearby to very relevant information 


# how to plot three way? 
# use example mzes of high and low lat for all the effects for visualization 



data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, Lateralized, Obs.No) %>% summarise(mean_awareness= mean(Aware.ReportObs), mean_sVGC= mean(sVGC.Obs), mean_dVGC= mean(dVGC.Obs),lat_sVGC= mean(hor_values_sVGC), lat_dVGC= mean(hor_values_dVGC))

# remove intercept of each maze 
temp=data_plot %>% group_by(grid, Lateralized) %>% summarise(mean_awareness= mean(mean_awareness), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_awareness= data_plot$mean_awareness-  rep(temp$mean_awareness, each=6)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=6)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=6)

ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_sVGC, fill= lat_sVGC, group = factor(lat_sVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_continuous_lateralized_horizontal_sVGC.pdf', device = "pdf", width= 7, height =5)

ggplot(data_plot, aes(x=mean_dVGC, y= mean_awareness, color=lat_dVGC, fill= lat_dVGC, group = factor(lat_dVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1))

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_continuous_lateralized_horizontal_dVGC.pdf', device = "pdf", width= 7, height =5)


# plot three way interaction effect now 
data_plot= data

# summarize by maze 
data_plot= data %>% group_by(grid, Lateralized, Obs.No) %>% summarise(mean_awareness= mean(Aware.ReportObs), mean_sVGC= mean(sVGC.Obs), mean_dVGC= mean(dVGC.Obs),lat_sVGC= mean(lateralized_values_sVGC), lat_dVGC= mean(lateralized_values_dVGC), hlat_sVGC= mean(hor_values_sVGC), hlat_dVGC= mean(hor_values_dVGC))

data_plot$Hor_Lat_binsVGC= data_plot$hlat_sVGC >= 0.49
data_plot$Hor_Lat_bindVGC= data_plot$hlat_dVGC >= 0.5

# remove intercept of each maze 
temp=data_plot %>% group_by(grid, Lateralized) %>% summarise(mean_awareness= mean(mean_awareness), mean_sVGC= mean(mean_sVGC), mean_dVGC= mean(mean_dVGC))

data_plot$mean_awareness= data_plot$mean_awareness-  rep(temp$mean_awareness, each=6)
data_plot$mean_sVGC= data_plot$mean_sVGC-  rep(temp$mean_sVGC, each=6)
data_plot$mean_dVGC= data_plot$mean_dVGC-  rep(temp$mean_dVGC, each=6)

ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_sVGC, fill= lat_sVGC, group = factor(lat_sVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('sVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1)) + facet_wrap(~Hor_Lat_binsVGC)

ggsave('~/Documents/ValueBasedConstrualTask/value-guided-construal-main/datapilot/interaction_plot_continuous_lateralized_horizontal_sVGC.pdf', device = "pdf", width= 7, height =5)

ggplot(data_plot, aes(x=mean_sVGC, y= mean_awareness, color=lat_dVGC, fill= lat_dVGC, group = factor(lat_dVGC)))+  geom_point() + theme_classic() + xlab("") +  ylab("awareness reports (scaled)") + xlab('dVGC (scaled)')  + theme(axis.text.x = element_text(size=14), axis.title.y = element_text(size=14), axis.text.y = element_text(size=14)) + geom_smooth(aes( color=lat_sVGC, fill= lat_sVGC), method='lm', se= FALSE, fullrange = T) +  colorspace::scale_color_continuous_sequential(palette = 'Orange', limits = c(0,1)) + colorspace::scale_fill_continuous_sequential(palette = 'Orange',limits = c(0,1)) + facet_wrap(~Hor_Lat_bindVGC)

```


```{r block effects peliminary model}

library(lme4)
data$Block[data$Trial.Number < 72] =1
data$Block[data$Trial.Number >=72 & data$Trial.Number < 144] =2
data$Block[data$Trial.Number >=144 & data$Trial.Number < 216] =3
data$Block[data$Trial.Number >=216 & data$Trial.Number < 288] =4

data$sVGC.Obs.zscore= scale(data$sVGC.Obs)[,1]
data$dVGC.Obs.zscore= scale(data$dVGC.Obs)[,1]
data$Lateralized.zscore= scale(data$Lateralized)[,1]

# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block, data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block+ sVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block + sVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ Block+ sVGC.Obs.zscore * Lateralized.zscore, data= data)
lm4= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ Block+ sVGC.Obs.zscore * Lateralized.zscore*Block, data= data)
anova(lm0,lm1, lm2, lm3, lm4)

sjPlot::tab_model(lm3)
# significant interaction effect between awareness and sVGC, better fits (stronger relationship, when lateralized )


# need to add subject intercept!!
lm0= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block, data= data)
lm1= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block+ dVGC.Obs.zscore, data= data)
lm2= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code) + Block + dVGC.Obs.zscore + Lateralized.zscore, data= data)
lm3= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ Block+ dVGC.Obs.zscore * Lateralized.zscore, data= data)
lm4= lmer(Aware.ReportObs.scaled ~  (1 | MazeID) + (1 | Subject.Code)+ Block+ dVGC.Obs.zscore * Lateralized.zscore*Block, data= data)
anova(lm0,lm1, lm2, lm3, lm4)

sjPlot::tab_model(lm3)
# we observe the same thing for the dynamic construals 


# small effect of block for both sVGC and dVGC
# but this block effect does not interact with our interaction effect of interest! 
# this means that while participants are less likely to report being aware of an obstacle with increasing trials, this does not impact the effect of the model or lateralization effects 
# so our lateralization effect is not bc people are tired 
```